### ISSUE TITLE
加入事务控制

### ISSUE THREAD

**Issue by ghfhfgwr3** [APIJSON/APIJSON#105]
今天和同事沟通，我把apijson集成到会员管理系统了。实际中出现断网情况，消费机通过apijson写的数据，会不会写不进去。涉及到里面apijson有没有涉及到事务的处理。同时之前操作好像是消费机下发数据给我们，但作为服务端的我们去操作数据库，本身涉及到业务逻辑的代码在会员管理系统写好了。现在是apijson直接操作数据库，然后会员管理系统也直接操作数据库，走的是两个路。

**Comment by TommyLemon** [comment]
感谢建议。

请问是哪家公司呢？
https://github.com/APIJSON/APIJSON/issues/73

**Comment by TommyLemon** [comment]
已加上
https://github.com/APIJSON/APIJSON/commit/5810ecf388e352c684760a40f12348eeecc4b544
