### ISSUE TITLE
是否支持不同字段的or 

### ISSUE THREAD

**Issue by Cole-Mu** [APIJSON/APIJSON#107]
例子里是一个字段的or ，但有时需要  (name='xxx' or id=1 ) and status=‘normal’ 这种sql，是否支持呢

**Comment by TommyLemon** [comment]
https://github.com/APIJSON/APIJSON/issues/84

**Comment by wang1784594241** [comment]
> #84
这个我看了啊，只找到这个
"id{}":"<=80000,>90000"  单字段
可是这也不能举一反三就知道怎么写多字段or啊

**Comment by TommyLemon** [comment]
@wang1784594241 你的评论怎么不见了？我在通知里还看到这个
"这个我看了啊，只找到这个 "id{}":"<=80000,>90000" 单字段 可是这也不能举一反三就知道怎么写多字段or啊"

**Comment by TommyLemon** [comment]
像上面那个例子，不考虑 id 为主键的话，可以
```js
{
    "Table": {  //具体的表名
        "name": "xxx",
        "id": 1,
        "status": "normal",
        "@combine": "name,id"  //或者 "|name,|id"
    }
}
```

**Comment by Cole-Mu** [comment]
感谢，原来文档里也有，只是没这么详细，之前没看明白，这下理解了。

**Comment by zhangchunlin** [comment]
我在 uliweb-apijson里不支持 @combine ，而是另外支持 @expr 这样一个更灵活的格式，可以支持比较复杂的表达，供参考，例子：
```
"user":{
    "@column":"id,username,nickname,email",
    "@order":"id-",
    "@role":"ADMIN",
    "@expr":[["username$","|","email$"],"&",["!","nickname$"]],
    "username$":"%b%",
    "email$":"%@example.com",
    "nickname$":"%c%",
}
```

**Comment by TommyLemon** [comment]
> 我在 uliweb-apijson里不支持 @combine ，而是另外支持 @expr 这样一个更灵活的格式，可以支持比较复杂的表达，供参考，例子：
> 
> ```
> "user":{
>     "@column":"id,username,nickname,email",
>     "@order":"id-",
>     "@role":"ADMIN",
>     "@expr":[["username$","|","email$"],"&",["!","nickname$"]],
>     "username$":"%b%",
>     "email$":"%@example.com",
>     "nickname$":"%c%",
> }
> ```

可以加个链接方便打开项目查看

**Comment by martin-1120** [comment]
这种同一个字段要多次用的呢
(
age = 10
 )
or
(
age > 20 and status =1
)

**Comment by TommyLemon** [comment]
> 这种同一个字段要多次用的呢 ( age = 10 ) or ( age > 20 and status =1 )

@martin-1120 

"@combine":"age | (age> & status)", // 任意与或非条件组合
"age":10,
"age>"20,
"status":1

**Comment by martin-1120** [comment]
如果我想这样呢，会报错 ***@***.***":"age&gt; | (age&gt; &amp; status)", // 任意与或非条件组合

"age&gt;"20,
"status":1


报错的意思是：数量不匹配 字段有两个 combine有三个

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TommyLemon ***@***.***&gt;
发送时间: 2023年12月17日 13:07
收件人: Tencent/APIJSON ***@***.***&gt;
抄送: 小云 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Tencent/APIJSON] 是否支持不同字段的or  (#107)





  
这种同一个字段要多次用的呢 ( age = 10 ) or ( age &gt; 20 and status =1 )
  
@martin-1120
 
***@***.***":"age | (age&gt; &amp; status)", // 任意与或非条件组合
 "age":10,
 "age&gt;"20,
 "status":1

**Comment by TommyLemon** [comment]
@martin-1120 你直接在 GitHub 上回复，不要用邮箱回复，现在代码有不少乱码，很难看

**Comment by martin-1120** [comment]
@TommyLemon  
如果我想这样呢  
一：
status=1  | (status=2  & age=20)  

二：
status=1  | (status=1  & age=20) 

二 我试过会报错 :
报错的意思是：数量不匹配 字段有两个 combine有三个

**Comment by TommyLemon** [comment]
@martin-1120 

DemoSQLConfig 重写 getMaxCombineRatio ，return 0

**Comment by martin-1120** [comment]
@TommyLemon  第一种呢  
一：
status=1 | (status=2 & age=20)

**Comment by TommyLemon** [comment]
一样。
只不过 JSON 的 key 不支持重名，需要换一种写法：
"status":1,
"status{}":"=2" 或 "status{}":[2]

**Comment by martin-1120** [comment]
@TommyLemon 就是重名怎办呢，比如有三个重名？没办法了吗
status=1 | (status=2 & age=20) | (status=3 & age=30)

**Comment by martin-1120** [comment]
建议是不是能像这样用冒号增加别名, 这样就很完善了
"status:status1":1,
"status:status2 ":2,
"status:status3 ":3,
"age:age20": 20,
"age:age30": 30,
"@combine":"status1 | (status2 & age20) | (status3 & age30)"

**Comment by TommyLemon** [comment]
还可以
"status&{}": "=1",
"status|{}": "=2"

你举得例子几乎不会实际出现在业务中，一般一个字段最多同时传两个条件

**Comment by TommyLemon** [comment]
> 建议是不是能像这样用冒号增加别名, 这样就很完善了 "status:status1":1, "status:status2 ":2, "status:status3 ":3, "age:age20": 20, "age:age30": 30, "[@combine](https://github.com/combine)":"status1 | (status2 & age20) | (status3 & age30)"

@martin-1120  6.3.0+ 可以用 @key 映射字段
https://github.com/Tencent/APIJSON/releases/tag/6.3.0

"@key":"status1:(status);status2:(status);status3:(status)",
"status1": 1,
"status2": 2,
"status3": 3
