### ISSUE TITLE
本质上是贫血模型，一个ORM工具，几乎无法定制自己的业务

### ISSUE THREAD

**Issue by liupeizhi** [APIJSON/APIJSON#110]
API直接到DB了，SQL是自己封装的，对于复杂业务来说无法定制SQL，优化更无从谈起，但是毕竟适合简单业务，做一个快速的原型项目还是可以的
其实思想是挺好的，与GraphQL比较类似，感觉API未来的格式有可能就是这一种

**Comment by TommyLemon** [comment]
APIJSON 提供了 远程函数 ，可以扩展自己的业务逻辑
https://github.com/APIJSON/APIJSON/issues/101
