### ISSUE TITLE
请求api时date区间条件怎么设置

### ISSUE THREAD

**Issue by bpmbank** [APIJSON/APIJSON#112]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
{
    "User": {
        "date{}": ">=2017-02"
    }
}

**错误信息**

- 测试账号 +
 {
"User":  {
"date{}": ">=2017-02"
},
"code": 403 ,
"msg": "date{}:value 的 value 中 >=2017-02 不合法！预编译模式下 key{}:"condition" 中 condition 必须 为 =null 或 !=null 或 符合正则表达式 ^[0-9%!=<>,]+$ ！不允许空格！" ,
"sql:generate|cache|execute|maxExecute": "1|0|0|200" ,
"depth:count|max": "1|5" ,
"time:start|duration|end": "1572353867665|4|1572353867669"
}

时间区间的条件该如何设置？

**Comment by TommyLemon** [comment]
比较运算
"date>=": "2017-02"

连续范围
"date%": "2017-02,2018-02"

https://github.com/APIJSON/APIJSON/blob/master/Document.md#32-%E5%8A%9F%E8%83%BD%E7%AC%A6

**Comment by shanhan0** [comment]
搜索日期和时间区间也是一样的吗   "2017-02-01 10:01:02 ,2018-02-01 11:09:03"

**Comment by TommyLemon** [comment]
> "2017-02-01 10:01:02 ,2018-02-01 11:09:03"

一样，不过你写的这个在逗号前多了个空格

**Comment by shanhan0** [comment]
好的，感谢回答

**Comment by transtone** [comment]
pg使用此查询方式前，数据库连接加参数 `stringtype=unspecified`
https://github.com/Tencent/APIJSON/issues/436
