### ISSUE TITLE
这个好像和 GraphQL  作用类似吧？

### ISSUE THREAD

**Issue by anonymoustoken** [APIJSON/APIJSON#12]
这个好像和 GraphQL  作用类似吧？
为啥要重新做一个？
是不是为了弥补 GraphQL  的某个缺陷？

**Comment by TommyLemon** [comment]
GraphQL 是 API Proxy, APIJSON 是 ORM 库
https://github.com/TommyLemon/APIJSON/issues/2
可以结合使用
https://github.com/AutoGraphQL/AutoGraphQL
