### ISSUE TITLE
query为2时仍无法查询所有数据

### ISSUE THREAD

**Issue by yoyogis** [APIJSON/APIJSON#134]
**环境信息**
官方环境：http://apijson.org/auto/

**问题描述**
按照文档的说法，query为2时将查询所有的数据并返回，但是实际只返回了10条数据。

query为2时仍无法查询所有数据。如图：
![image](https://user-images.githubusercontent.com/1673082/82975372-d6aefd00-a00e-11ea-97da-cae9440bf5b5.png)

查询参数为
```
{
    "User[]": {
        "User": {
            "@column": "id"
        },
        "query": 2
    },
    "total@": "/User[]/total"
}
```
输出为
 ```
{
"User[]":  Array[10], // 此处收起来了，只查询出10个元素
"total": 139 ,
"ok": true ,
"code": 200 ,
"msg": "success" ,
"sql:generate|cache|execute|maxExecute": "11|9|2|200" ,
"depth:count|max": "3|5" ,
"time:start|duration|end": "1590550937156|4|1590550937160"
}
```

**Comment by TommyLemon** [comment]
query:2 - 全部 是指以上全部，就是同时查数据和总数。
可以设置 count: 0 来查最多能查的数量，默认 Parser.getMaxQueryCount 返回 100 条。
多余这个数量可以调整返回值，或者分页

**Comment by yoyogis** [comment]
哦，明白了 感谢回答
