### ISSUE TITLE
现在支持级联操作的增删改吗？

### ISSUE THREAD

**Issue by cndota123** [APIJSON/APIJSON#89]
有的业务需要增删改操作时作用于多个表还有批量增，有对应的支持吗？文档没有看到

**Comment by TommyLemon** [comment]
你标题里说的 “级联“ 就是指内容里说的 “多个表” ？
这种的有 Demo，例如 register，在 Request.sql 表里有。

批量删除文档里有的，Demo 也有
https://github.com/APIJSON/APIJSON/blob/master/Document.md#3.1

**Comment by TommyLemon** [comment]
批量新增也已支持，还是见这个文档
https://github.com/APIJSON/APIJSON/blob/master/Document.md#3.1
