### ISSUE TITLE
APIJSON 怎么很好的跟分布式缓存结合呢？

### ISSUE THREAD

**Issue by karosLi** [APIJSON/APIJSON#90]

**Comment by TommyLemon** [comment]
可使用现有的分布式缓存架构，APIJSON ORM 只单独在各个节点的 Server 对接数据库，
在 [DemoSQLExecutor](https://github.com/APIJSON/APIJSON/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/demo/server/DemoSQLExecutor.java) 重写 [AbstractSQLExecutor](https://github.com/APIJSON/APIJSON/blob/master/APIJSON-Java-Server/APIJSONORM/src/main/java/zuo/biao/apijson/server/AbstractSQLExecutor.java) putCache 和 removeCache，使用 Redis 等库来实现自定义的缓存
