### ISSUE TITLE
关于事务操作

### ISSUE THREAD

**Issue by cndota123** [APIJSON/APIJSON#91]
文档提到是支持事务的，但是没看到对应的功能具体描述，而且看了代码跑了一遍也没看到有事务相关操作，如何开启事务呢？

**Comment by TommyLemon** [comment]
APIJSON 本身没有实现事务功能，但操作单表是可以由数据库保证事务的，
失败了不会产生脏数据，和操作多表回滚效果一样，
所以建议只用来操作单表，也就是“简单的事务操作”。

**Comment by TommyLemon** [comment]
APIJSON 3.7.0 已支持多表操作的事务
https://github.com/APIJSON/APIJSON/releases/tag/3.7.0
