### ISSUE TITLE
oracle版本停止更新了吗？

### ISSUE THREAD

**Issue by xlabwj** [APIJSON/APIJSON#96]
APIJSONBootOracle 项目编译不通过DemoSQLExecutor类protected Object getValue(SQLConfig config, ResultSet rs, ResultSetMetaData rsmd, int tablePosition,
			JSONObject table, int columnIndex, Map<String, JSONObject> childMap)方法编译报错，提示父类没有getValue方法

**Comment by TommyLemon** [comment]
注释/删除这个方法即可，已更新
https://github.com/APIJSON/APIJSON
