### ISSUE TITLE
AbstractSQLExecutor能否对关联查询一次性获取父容器的字段值再执行子容器的查询

### ISSUE THREAD

**Issue by dodomao** [APIJSON/APIJSON#97]
**具体说下**
AbstractSQLExecutor如何对关联查询一次性获取父容器的字段值再执行子容器的查询，比如：User 和 Comment[]，能否缓存userid再一次性返回子容器的集合，避免N+1的问题，类似Graphql的解决办法：
 1.先将要查询的字段先存起来
 2.在resolve的GraphQL\Deferred返回一个Promise, 这个Promise不会真正查询数据.
 3.当所有的逻辑全部执行完毕后, 才会真正查询数据库.

**为什么**
提升apijson的执行效率和节省数据库访问次数，防止访问数据量大的时候拖慢Server的性能

**Comment by TommyLemon** [comment]
APIJSON 自动化的 APP JOIN 相当于 GraphQL 手动写的 DataLoader，
还提供了 LEFT JOIN, RIGHT JOIN, INNER JOIN 等 SQL JOIN。

见 功能符/数组关键词 ④ "join":"&/Table0/key0@,</Table1/key1@" 多表连接方式
https://github.com/APIJSON/APIJSON/blob/master/Document.md#3.2

**Comment by StickChen** [comment]
join 只能解决一对一或者多对一，常见的一对多不行

**Comment by TommyLemon** [comment]
> join 只能解决一对一或者多对一，常见的一对多不行
@StickChen 
https://github.com/Tencent/APIJSON/issues/374
